<?php session_start(); ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./style/reception.css">
    <title>Document</title>
</head>
<body>
    <header>
        <img src="./images/logo.svg" height="70" class="logo" alt="logo">
        <div class="profilenav">
            <img src="./images/avatar-01.jpg" height="50" class="avatar" alt="profile picture">
            <p class="Pseudo"><?php echo $_SESSION['Pseudo']; ?></p>
            <a href="logout.php">
                <div class="logout">
                    <img src="./images/logout.png" height="50" class="avatar" alt="logout icon">
                    <p class="Pseudo">Logout</p>
                </div>
            </a>
        </div>
    </header>
    <div class="side-bar">
        <nav>
            <a href="mail.php"><button>Ecrire</button></a>
            <ul>
                <li><a href="reception.php">Boite reception</a></li>
                <li><a href="nonlus.php">Non lus</a></li>
                <li><a href="envoyes.php">Envoyer</a></li>
                <li><a href="corbeille.php">Corbeille</a></li>
            </ul>
        </nav>
    </div>
    <div class="disp">
        zzz
    </div>
</body>
</html>












